#DataBase mem H2

server:
  port: 3000

spring:
  datasource:
    h2:
      console:
        enabled: true
        path: /h2-console
    jpa:
      show-sql: true
      database-platform: org.hibernate.dialect.H2Dialec
      hibernate:
        ddl-auto: create-drop
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:post;DB_CLOSE_DELAY=-1
    username: admin
    password: admin
